language: c++
# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - cmake
    - ninja-build

before_install:
    - eval "${MATRIX_EVAL}"

script:
- mkdir build
- cd build
- cmake -DHAVE_SSE4_1=1 .. && ninja

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - mpi-default-dev
      env:
        - MATRIX_EVAL="CXX=g++-4.8"
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - mpi-default-dev
      env:
        - MATRIX_EVAL="CXX=g++-7"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - mpi-default-dev
            - libc++-dev
      env:
        - MATRIX_EVAL="CXX=clang++-3.6"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - mpi-default-dev
            - libc++-dev
      env:
        - MATRIX_EVAL="CXX=clang++-4.0"
