build: off  # disable msbuild

environment:
  matrix:
    - SCRIPT: C:\cygwin64\bin\bash.exe .appveyor/cygwin-compile.sh
    - SCRIPT: .appveyor/msvc-compile.bat
      VSVERSION: 140

install:
#- git clone -q --branch=appveyor-cygwin https://github.com/soedinglab/mmseqs2 C:\projects\mmseqs2
 - mkdir C:\projects\mmseqs2\build
 - cd C:\projects\mmseqs2\build
 - CXX=g++ cmake .. 
 - make 
