build: off

environment:
    CYG_MIRROR: http://cygwin.mirror.constant.com
    CYG_PACKAGES: bash,xxd,cmake,make,gcc-core,gcc-g++,zlib-devel,libbz2-devel,busybox-standalone,git,binutils
    matrix:
        - CYG_ROOT: C:\cygwin64
          CYG_CACHE: C:\cygwin64\var\cache\setup
          CYG_SETUP: C:\cygwin64\setup-x86_64.exe 
          BASH: C:\cygwin64\bin\bash

cache:
    - C:\cygwin64\var\cache\setup

init:
    - git config --global core.autocrlf input

install:
    - if defined CYG_ROOT (%CYG_SETUP% --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages "%CYG_PACKAGES%" --upgrade-also)

build_script:
    - if defined BASH (%BASH% -lc "./util/build_windows.sh $(cygpath %APPVEYOR_BUILD_FOLDER%) $(cygpath %APPVEYOR_BUILD_FOLDER%)/build")
