build: off  # disable msbuild


environment:
    CYG_MIRROR: http://cygwin.mirror.constant.com
    CYG_PACKAGES: make,gcc-core,clang,pkg-config,libpcre-devel,cmake,xxd,python-setuptools,ruby
    MSYS_PACKAGES: cmake
    matrix:
        - CYG_ROOT: C:\cygwin64
          CYG_CACHE: C:\cygwin64\var\cache\setup
          CYG_SETUP: C:\cygwin64\setup-x86_64.exe 
          BASH: C:\cygwin64\bin\bash
          CC: gcc

install:
 - if defined CYG_ROOT (%CYG_SETUP% --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages "%CYG_PACKAGES%" --upgrade-also)
build_script:
 - if defined BASH (%BASH% -lc "mkdir $(cygpath ${APPVEYOR_BUILD_FOLDER})/build && cd $(cygpath ${APPVEYOR_BUILD_FOLDER})/build && cmake .. && make")
#- git clone -q --branch=appveyor-cygwin https://github.com/soedinglab/mmseqs2 C:\projects\mmseqs2
